### ISSUE TITLE
WebRTC data channel

### ISSUE THREAD

**Issue by sipsorcery** [forestrf/sctp4cs#1]
> This port was made to implement WebRTC with datachannels in another library that will link this one.

Did that ever eventuate?

**Comment by forestrf** [comment]
Yes, though I intended to sell it eventually, and because of reasons never happened. Also I only implemented datachannels, and only one. It's not a perfect implementation.

**Comment by sipsorcery** [comment]
Ok, Thanks taking the time to do the sctp4j port. I've used it in my [data channel implementation](https://github.com/sipsorcery/sipsorcery/blob/master/src/net/WebRTC/RTCPeerSctpAssociation.cs)
